name: build_repository_docker
on:

  push:
    branches: [ ros2_arducam ]

    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: ctu-mrs/ci_scripts/.github/workflows/build_repository_docker.yml@ros2
    with:
      base_image: ctumrs/mrs_uav_system_core:stable
      output_image: ctumrs/libcamera_ros_driver:arducam
      wait_for_ppa: false
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      DOCKERHUB: ${{ secrets.DOCKERHUB }}
